name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [self-hosted, ubuntu-gcp]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev libz3-dev pkg-config clang

    - name: Install solc-select
      run: |
        sudo apt-get install -y python3-pip
        pip3 install solc-select
        solc-select install 0.8.15
        solc-select use 0.8.15

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run integration tests
      run: python3 integration_test.py
